version: "3"

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    command: bash -c "python manage.py runserver 0.0.0.0:$SERVER_PORT"
    env_file:
      - .env
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_SERVER_API_URL=$SERVER_API_URL
